services:

  jupyter:
    build: .

    ports:
      - 8888:8888

    volumes:
      - ./source:/home/jovyan/source

    env_file:
      - .env

    networks:
      - langchain-net

    container_name: jupyter-container

  vs-db: # vector database based in postgres
    image: pgvector/pgvector:pg16

    env_file:
      - .env

    networks:
      - langchain-net

    container_name: pgvector-container

networks:
  langchain-net:
    name: langchain-net
    external: false